jenkinsci/warnings-ng-plugin

src/main/java/io/jenkins/plugins/analysis/warnings/Flake8.java

The flake8 parser requires that flake8 output in pylint format, not its default format.
This format can be achieved with `--format=pylint` or in a file `--config=path` ->
```
[flake8]
format=pylint
```
Link shows parser requiring pylint formatting of output.
https://github.com/tomasbjerre/violations-lib/blob/c3f597a65528544a99cb1c6dfa016299189065bc/src/main/java/se/bjurr/violations/lib/parsers/Flake8Parser.java#L20

Add required formatting option to docs

---

src/main/webapp/js/issues-detail.js

This is not exactly the ajax pagination but a simple hotfix to allow users use warnings ng plug-in even though they have much more than 1000+ elements in their warnings table.
Resource:
https://datatables.net/examples/ajax/defer_render.html
I am not sure how can I test this in action. It would be great having a way for getting *.hpi file and see it in our current Jenkins implementations with the builds more than 2k+ warnings.

JENKINS-49965 "Slow performance of warnings table if there are 1000 elements"

---

src/main/java/io/jenkins/plugins/analysis/core/model/TabLabelProvider.java
src/main/java/io/jenkins/plugins/analysis/warnings/PyLint.java

Continuation of my work in https://github.com/jenkinsci/analysis-model/pull/100.
I did two changes
* Adjust the help message for pylint in the snippet generator.
* Activate the `Package` tab in the details view when python files are found for the issues (instead of having a Folder tab).

Pylint: add proper support for packages and modules

---

src/main/java/io/jenkins/plugins/analysis/core/model/AggregationAction.java
src/main/java/io/jenkins/plugins/analysis/core/model/ResultAction.java
src/test/java/io/jenkins/plugins/analysis/core/model/AggregationActionTest.java

Pull request for: [JENKINS-56726](https://issues.jenkins-ci.org/browse/JENKINS-56726).
I'm having issues with testing `getApi()` and `getTools()`.
Is there a convenient way of mocking an `ResultAction` without mocking the entire codebase?
I'm constantly running into NullPointerExceptions while trying to test those methods.
@uhafner

[JENKINS-56726] Unit Tests for AggregationAction

---

src/main/java/io/jenkins/plugins/analysis/core/util/FileFinder.java

There are a couple of code paths that scan work spaces with the follow symlinks defaulted to true (specifically around resolving a project's modules).  This prevents those scans from following symlinks, which can cause problems with repositories with recursive links.
There is no clear way to make this configurable (e.g. the module paths are static fields on the class).  Given that Jenkins has a fair amount of control over pulling the files into it's workspace (e.g. fetch from source control), I think moving the default to false will be reasonably safe.

Default FileFinder to not follow symlinks.

---

src/test/java/io/jenkins/plugins/analysis/warnings/recorder/TokenMacroITest.java

Although usage of token-macro plugin does not work within integration-test pipeline job,
here the PR as agreed.

basic iTest for token-macro usage in cps-definition still not working

---

pom.xml
src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesAggregator.java
src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesPublisher.java
src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesRecorder.java
src/main/java/io/jenkins/plugins/analysis/core/steps/PublishIssuesStep.java
src/main/java/io/jenkins/plugins/analysis/core/steps/RecordIssuesStep.java
src/main/java/io/jenkins/plugins/analysis/core/util/QualityGateStatus.java
src/main/java/io/jenkins/plugins/analysis/core/util/QualityGateStatusHandler.java
src/main/resources/io/jenkins/plugins/analysis/core/steps/RecordIssuesStep/config.jelly
src/main/resources/io/jenkins/plugins/analysis/core/steps/RecordIssuesStep/config.properties
src/main/resources/io/jenkins/plugins/analysis/core/steps/RecordIssuesStep/help-aggregatingResults.html
src/main/resources/io/jenkins/plugins/analysis/core/steps/RecordIssuesStep/help-enabledForFailure.html
src/test/java/io/jenkins/plugins/analysis/core/util/QualityGateStatusHandlerTest.java
src/test/java/io/jenkins/plugins/analysis/core/util/QualityGateStatusTest.java
src/test/java/io/jenkins/plugins/analysis/warnings/StepsITest.java

See https://github.com/jenkinsci/workflow-api-plugin/pull/91 and [JENKINS-39203](https://issues.jenkins-ci.org/browse/JENKINS-39203). (I am intentionally not updating the status of that ticket or assigning it to myself until I am ready to merge/release all relevant changes to avoid giving users premature hope of a fix and so that I have clear answers for what will and won't work and when any fixes will be released.)
This PR adds a `WarningAction` to the `StepAtomNode` for `publishIssues` steps that complete with `QualityGateStatus.WARNING` so that the actual stage containing the `publishIssues` step can be visualized as unstable via https://github.com/jenkinsci/pipeline-graph-analysis-plugin/pull/25. The PR also incrementalifies the plugin (See …

[JENKINS-39203] Mark publishIssues steps with QualityGateStatus.WARNING with WarningAction

---

doc/Documentation.md

Describe how to create a Groovy parser with a Groovy script, e.g in the script console.
related to [JENKINS-52237](https://issues.jenkins-ci.org/browse/JENKINS-52237)

add description for programmatic Groovy parser creation

---

src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesRecorder.java
src/main/java/io/jenkins/plugins/analysis/core/steps/PublishIssuesStep.java
src/test/java/io/jenkins/plugins/analysis/warnings/StepsITest.java

See https://issues.jenkins-ci.org/browse/JENKINS-58977.

Use the default ID `analysis` for multiple reports if no ID is given (JENKINS-58977)

---

.travis.yml
src/main/java/io/jenkins/plugins/analysis/core/steps/AnnotatedReport.java
src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesAggregator.java
src/test/java/io/jenkins/plugins/analysis/core/steps/IssuesAggregatorTest.java

See [JENKINS-59178](https://issues.jenkins-ci.org/browse/JENKINS-59178).

[JENKINS-59178] Fix NPE when aggregating different results in matrix build

---

pom.xml

There is no need to have it as an optional dependency anymore.

Remove git-forensics dependency, add it as integration test dependency

---

src/main/java/io/jenkins/plugins/analysis/core/model/DeltaReport.java
src/test/java/io/jenkins/plugins/analysis/warnings/recorder/QualityGateITest.java

The first build should always have a passed quality gate if the type is set to new warnings or delta warnings.

[JENKINS-58635] Do not fail quality gate for the first build

---

pom.xml

See [JENKINS-59172](https://issues.jenkins-ci.org/browse/JENKINS-59172). The goal is to avoid duplicating effort updating docs in two places.

[JENKINS-59172] load documentation from GitHub

---

src/main/java/io/jenkins/plugins/analysis/core/charts/HealthTrendChart.java
src/main/java/io/jenkins/plugins/analysis/core/charts/LinesChartModel.java
src/main/java/io/jenkins/plugins/analysis/core/charts/LinesDataSet.java
src/main/java/io/jenkins/plugins/analysis/core/charts/NewVersusFixedTrendChart.java
src/main/java/io/jenkins/plugins/analysis/core/charts/SeriesBuilder.java
src/main/java/io/jenkins/plugins/analysis/core/charts/SeverityTrendChart.java
src/main/java/io/jenkins/plugins/analysis/core/charts/ToolsTrendChart.java
src/main/webapp/js/simple-trend-chart.js
src/test/java/io/jenkins/plugins/analysis/core/charts/LinesChartModelTest.java
src/test/java/io/jenkins/plugins/analysis/core/charts/LinesDataSetTest.java
src/test/java/io/jenkins/plugins/analysis/core/charts/SeverityTrendChartTest.java

See [JENKINS-56264](https://issues.jenkins-ci.org/browse/JENKINS-56264). 
The trend chart on the job page should use the build number in URLs. The URL is used when clicking into the trend chart at the specific x-axis position.

[JENKINS-56264] Use build numbers in URLs, not display name

---

src/main/resources/io/jenkins/plugins/analysis/core/portlets/IssuesChartPortlet/portlet.jelly

See [JENKINS-57857](https://issues.jenkins-ci.org/browse/JENKINS-57857): adds a unique ID to the chart portlet divs so that multiple charts can be placed on the same view.

[JENKINS-57857] Add a unique ID to the chart divs.

---

etc/pmd-configuration.xml
src/main/java/io/jenkins/plugins/analysis/core/charts/CompositeResult.java
src/test/java/io/jenkins/plugins/analysis/core/charts/BuildResultStubs.java
src/test/java/io/jenkins/plugins/analysis/core/charts/CompositeResultTest.java
src/test/java/io/jenkins/plugins/analysis/core/charts/HealthTrendChartTest.java
src/test/java/io/jenkins/plugins/analysis/core/charts/NewVersusFixedTrendChartTest.java
src/test/java/io/jenkins/plugins/analysis/core/charts/SeverityPieChartTest.java
src/test/java/io/jenkins/plugins/analysis/core/charts/SeveritySeriesBuilderTest.java
src/test/java/io/jenkins/plugins/analysis/core/charts/SeverityTrendChartTest.java

See [JENKINS-58826](https://issues.jenkins-ci.org/browse/JENKINS-58826).
The number of builds which are included into a trend chart is currently limited by the fixed number of 50 builds. This limit is currently only working correctly in single trend charts. In aggregations (and charts with days as domain axis), this limit is applied on the wrong side, i.e. the charts are showing the first 50 builds and not the last 50 builds.

[JENKINS-58826] Fix visible number of build results in charts

---

src/main/java/io/jenkins/plugins/analysis/core/util/AbsolutePathGenerator.java
src/test/java/io/jenkins/plugins/analysis/core/util/AbsolutePathGeneratorTest.java

Catch all exceptions during resolving of absolute paths.
Fixes: 
- https://issues.jenkins-ci.org/browse/JENKINS-59986
- https://issues.jenkins-ci.org/browse/JENKINS-60033

[JENKINS-59986] Handle broken paths silently

---

pom.xml
src/main/java/io/jenkins/plugins/analysis/core/util/ModelValidation.java
src/main/resources/io/jenkins/plugins/analysis/core/steps/IssuesRecorder/help-id.html
src/main/resources/io/jenkins/plugins/analysis/core/steps/PublishIssuesStep/help-id.html
src/main/resources/io/jenkins/plugins/analysis/core/steps/RecordIssuesStep/help-id.html
src/main/resources/io/jenkins/plugins/analysis/core/steps/ScanForIssuesStep/help-id.html
src/test/java/io/jenkins/plugins/analysis/core/model/LabelProviderFactoryITest.java
src/test/java/io/jenkins/plugins/analysis/core/util/ModelValidationTest.java

Now allowed characters in IDs are: 
- alphanumeric characters (lowercase)
- dashes
- underscores.

Add underscores to the allowed set of characters for IDs.

---

pom.xml
src/main/java/io/jenkins/plugins/analysis/warnings/axivion/RemoteAxivionDashboard.java
src/test/java/io/jenkins/plugins/analysis/warnings/axivion/TestDashboard.java

Push configuration of static analysis tools and all common test dependencies into a new [parent pom](https://github.com/jenkinsci/analysis-pom-plugin).

Use new parent pom

---

src/test/java/io/jenkins/plugins/analysis/core/model/IconLabelProviderTest.java

[JENKINS-59617](https://issues.jenkins-ci.org/browse/JENKINS-59617) I have one question for this test. During the test, I have to access the ICONS_URL field which is static and private in the original class, so in order not to use reflection or add additional getter in the original class, I create a same field in this test class. I don't know whether this solution is correct.

[JENKINS-59617] Create unit test for IconLabelProvider

---

src/main/java/io/jenkins/plugins/analysis/core/model/Blame.java
src/main/java/io/jenkins/plugins/analysis/core/model/BlamesModel.java
src/test/java/io/jenkins/plugins/analysis/core/model/BlameTest.java
src/test/java/io/jenkins/plugins/analysis/warnings/StepsITest.java

Since mapping of blames will be required in several places (see https://github.com/jenkinsci/warnings-ng-plugin/pull/389) it makes sense to encapsulate that behavior in a common place.

Add a Blame model object that encapsulates mapping of blames to issues

---

doc/Documentation.md

Documentation was unclear on what values the `type` parameter to the Token Macro `ANALYSIS_ISSUES_COUNT` accepted.
One of the examples appears to have a syntax error.
May be related to: [JENKINS-61593](https://issues.jenkins-ci.org/browse/JENKINS-61593)

Update token macro documentation

---

Jenkinsfile
plugin/src/main/java/io/jenkins/plugins/analysis/core/util/Sanitizer.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/recorder/TokenMacroITest.java
plugin/src/test/resources/io/jenkins/plugins/analysis/warnings/recorder/all-severities.xml

See https://issues.jenkins-ci.org/browse/JENKINS-61593.
Since the test is successful, maybe the main problem was the wrong documentation. The documentation has been fixed with https://github.com/jenkinsci/warnings-ng-plugin/pull/434.

Add test case that tries to expose JENKINS-61593

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/model/SourcePrinter.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/SourcePrinterTest.java

In reference to [JENKINS-56699](https://issues.jenkins-ci.org/browse/JENKINS-56699). Added a method to replace new lines with `<br>` in messages. Added test for new lines.

[JENKINS-56699] Replace newlines `\n` with HTML equivalent `<br>` tags

---

doc/Documentation.md
ui-tests/src/main/java/io/jenkins/plugins/analysis/warnings/GlobalWarningsSettings.java
ui-tests/src/main/java/io/jenkins/plugins/analysis/warnings/GroovyConfiguration.java
ui-tests/src/main/java/io/jenkins/plugins/analysis/warnings/IssuesRecorder.java
ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/AbstractUiTest.java
ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/GlobalConfigurationUiTest.java
ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/WarningsPluginUiTest.java
ui-tests/src/test/resources/groovy_parser/pep8Test.txt

@uhafner: Ich stoße leider gerade auf eine Wand. Ich hoffe, Sie könnten mir eventuell weiter helfen :)
Und zwar habe ich mich für den Test an ```AffectedFilesResolverITest#shouldShowFileOutsideWorkspaceIfConfigured()``` gehalten.
Den Testaufbau habe ich absolut identisch, aber bei mir wird der Link zum Source Code irgendwie nicht erstellt. Das unterschiedliche Ergebnis lässt sich auf eine Zeile im Log zurück führen:
An meinem Orientierungstest wird die Datei mit den Issues gelesen und erkannt. Anschließend wird die Datei kopiert und es kommt zu folgender Log-Meldung:
```
[GNU C Compiler (gcc)] Creating fingerprints for all affected code blocks to track issues over different builds
[GNU C Compiler (gcc)] -> created fingerprints for 1 issues (skipped 0 issues)
[GNU C Compiler (gcc)] Copying …
```

JENKINS-60149: Add UI test for Global Configuration

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/model/DetailFactory.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/DetailFactoryTest.java

Rather than showing a generic title the breadcrumb should show the name of the Tool.

Fix title of origin breadcrumb

---

plugin/src/test/java/io/jenkins/plugins/analysis/core/model/JobActionTest.java

Added some basic unit tests. 
Untested methods use 'createBuildHistory()', which makes it hard to use mocks... I'm not sure how to get around this without some refactoring.

[JENKINS-59619] Create unit test for JobAction

---

plugin/pom.xml
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/AbstractDetailsModelTest.java

See https://github.com/jenkinsci/plugin-compat-tester/pull/249
I'm trying to make Warnings NG Plugin executable on PCT. Using a war with latest LTS and recent versions of plugins bundled on it, the execution throws some errors:
```
[INFO] Failed: 5
[INFO] - io.jenkins.plugins.analysis.core.model.BlamesModelTest.shouldShowIssueWithBlames
[INFO] - io.jenkins.plugins.analysis.core.model.BlamesModelTest.shouldShowIssueWithoutBlames
[INFO] - io.jenkins.plugins.analysis.core.model.ForensicsModelTest.shouldShowIssueWithForensics
[INFO] - io.jenkins.plugins.analysis.core.model.ForensicsModelTest.shouldShowIssueWithoutForensics
[INFO] - io.jenkins.plugins.analysis.core.model.IssuesModelTest.shouldConvertIssuesToArrayWithAllColumns
```
I've analysed the errors just in case the PCT was throwing some …

Update antisamy-markup-formatter-plugin version

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/WarningChecksPublisher.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/steps/WarningChecksPublisherITest.java
plugin/src/test/resources/io/jenkins/plugins/analysis/core/steps/pmd.xml

In some analysis reports (say spotbugs), issues can arise for multiple-lines of code, in this situation, we should ignore the columns when building the checks annotations, or GitHub will report validation failed.
See the context: https://github.com/jenkinsci/github-checks-plugin/issues/20

Ignore columns in multiple-line issues when building checks annotations

---

plugin/pom.xml
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesRecorder.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/PublishIssuesStep.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/WarningChecksPublisher.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/steps/WarningChecksPublisherITest.java

Update checks-api to 0.2.0 to adopt in-compatible new methods with task listener.
cc @timja

Update checks-api to 0.2.0

---

doc/Documentation.md
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/AggregationAction.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/restapi/ToolApi.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/AggregationActionTest.java

Former versions of analysis plugins included a count breakdown by severity in their APIs. In order to expose the counts by severity, one would need to call the current aggregation API, and then for each tool, call the `latestUrl` and count the issues by severity. Fortunately, the data is already available in a map, and just needs to be passed back in the response. This PR does that.
Initial attempts were to add this method to `ToolApi`
```
@Exported
public Map<Severity, Integer> getSizePerSeverity() {
...
}
```
but in the API response, the field was rendered as `sizePerSeverity: [63, 0, 0, 0]` instead of as a JSON map. Wasn't sure how to fix that, so I instead created 4 getters, one for each severity.
Assumption - That the `sizePerSeverity` map is not null and properly populated such that …

Include counts by severity in aggregation API response.

---

plugin/src/main/java/io/jenkins/plugins/analysis/warnings/tasks/TaskScanner.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/tasks/TaskScannerTest.java
plugin/src/test/resources/io/jenkins/plugins/analysis/warnings/tasks/file-with-tasks-and-ignore-section.txt

first draft of a solution for https://issues.jenkins-ci.org/browse/JENKINS-62944
not sure 
- if this is enough
- how and where to document this
@uhafner do you have some hints here?

[JENKINS-62944] Add exclude sections for task scanner

---

plugin/pom.xml
plugin/src/main/java/io/jenkins/plugins/analysis/core/filter/RegexpFilter.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/ReportScanningTool.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/Tool.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/AnalysisStepDescriptor.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesRecorder.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/axivion/AxivionSuite.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/axivion/RemoteAxivionDashboard.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/groovy/GroovyParser.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/tasks/OpenTasks.java
plugin/src/main/resources/io/jenkins/plugins/analysis/core/filter/RegexpFilter/config.jelly
plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/IssuesDetail/filled.jelly
plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/ReportScanningTool/config.jelly
plugin/src/main/resources/io/jenkins/plugins/analysis/warnings/axivion/AxivionSuite/config.jelly
plugin/src/main/resources/io/jenkins/plugins/analysis/warnings/groovy/GroovyParser/config.jelly
plugin/src/main/resources/io/jenkins/plugins/analysis/warnings/tasks/OpenTasks/config.jelly
plugin/src/main/resources/issues/health.jelly
plugin/src/main/resources/issues/publish-parameters.jelly
plugin/src/main/resources/issues/recorder.properties
plugin/src/main/resources/issues/scan-parameters.jelly
plugin/src/main/resources/issues/tool-defaults.jelly
plugin/src/main/resources/parser/advanced.jelly
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/PluginArchitectureTest.java

Downstream PR of jenkinsci/plugin-util-api-plugin#66. 
Use `@POST` for field validation. For details see https://www.jenkins.io/doc/developer/security/form-validation/.

Use @POST for form field validation

---

doc/Documentation.md
plugin/pom.xml
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesRecorder.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/PublishIssuesStep.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/RecordIssuesStep.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/WarningChecksPublisher.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/steps/WarningChecksPublisherITest.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/testutil/IntegrationTest.java

This PR adds support for the `withChecks` step recently added to the `checks-api` plugin, that allows for customization of published checks names by context.

Support withChecks

---

doc/Documentation.md
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesRecorder.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/PublishIssuesStep.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/RecordIssuesStep.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/WarningChecksPublisher.java
plugin/src/main/resources/issues/publish-parameters.jelly
plugin/src/main/resources/issues/publish-parameters.properties
plugin/src/test/java/io/jenkins/plugins/analysis/core/steps/WarningChecksPublisherITest.java
ui-tests/src/main/java/io/jenkins/plugins/analysis/warnings/IssuesRecorder.java
ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/FreeStyleConfigurationUITest.java

Improves several aspects of the checks layout:
- Use a more compact layout for the summary and details pane using tables. 
- Add a trend emoji indicator that shows if the project is improving or not.
- Show the reference build that is used to compute the new warnings.
- Add an optional option to show all warnings as annotations (and not only the new ones)

Improve layout of checks markup

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/WarningChecksPublisher.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/steps/WarningChecksPublisherITest.java

Otherwise the reference build will be shown inside the table, see https://github.com/jenkinsci/git-forensics-plugin/pull/213/checks?check_run_id=1717460354 for an example.

Add missing newline after GitHub checks details table

---

plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/IssuesRecorder/help-filters.html
plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/IssuesRecorder/help-id.html
plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/PublishIssuesStep/help-filters.html
plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/PublishIssuesStep/help-id.html
plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/RecordIssuesStep/help-filters.html
plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/RecordIssuesStep/help-id.html
plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/ScanForIssuesStep/help-filters.html
plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/ScanForIssuesStep/help-id.html

Inline documentation for `filter` contains the help of the `id` property. See https://issues.jenkins.io/browse/JENKINS-64702.

Add documentation for filters

---

plugin/src/main/resources/issues/property.jelly

If a tooltip is too big, and when it's positioned above the link, it can cover the link when there's not enough space. The link can't be clicked anymore at that point, since it's covered by the tooltip
Also, the tooltip will start to flicker.
Similar behavior is described [here](https://stackoverflow.com/questions/11979837/twitter-bootstrap-tooltip-not-aligning-correctly-when-it-is-going-to-go-outside).
Given the layout of the webpage, I think it's reasonable to always put the tooltip on the right, to avoid these issues.
I don't know how to add a test for this though. My experience with testing bootstrap and jelly files is limited...

[JENKINS-61484] tooltip will not cover link when placed right

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/model/JobAction.java
plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/JobAction/floatingBox.jelly

Possible solution for Jenkins-56594 bug. Created a noWarnings() method to iterate through results and return true if it finds no warnings. Added check in floatingbox.jelly to display congratulations message if from has no warnings.

[JENKINS-56594] - Hide empty trend charts

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/util/AffectedFilesResolver.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/util/AffectedFilesResolverTest.java

Replace handmade path comparison with `Path.startsWith`. Should fix the path detection problems on Windows (case insensitive paths).
See [JENKINS-63782](https://issues.jenkins.io/browse/JENKINS-63782)

[JENKINS-63782] Ignore case when comparing paths on Windows 

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/model/DetailsTableModel.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/DetailsTableModelTest.java

See [JENKINS-64051](https://issues.jenkins.io/browse/JENKINS-64051) for details.

[JENKINS-64051] Do not reformat punctuation when building the description 

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/model/AnalysisResult.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesRecorder.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/RecordIssuesStep.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/util/StaticAnalysisRun.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/StepsITest.java

The step now returns a list of `AnalysisResult` instances.
See https://issues.jenkins.io/browse/JENKINS-63109 for details.

[JENKINS-63109] Add a return value for the step `recordIssues`

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesScanner.java

Do not fail the build if the post processing steps produce an error. 
See [JENKINS-63010](https://issues.jenkins.io/browse/JENKINS-63010)

[JENKINS-63010] Catch `InvalidPathException` and report error.

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/AnalysisStepDescriptor.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/steps/AnalysisStepDescriptorTest.java

See [JENKINS-62415](https://issues.jenkins.io/browse/JENKINS-62415) for details.

[JENKINS-62415] Print parameters of step in Pipeline Steps View (flowGraphTable)

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/model/JobAction.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/ResultAction.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/StaticAnalysisLabelProvider.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/JobActionTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/StaticAnalysisLabelProviderTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/util/SanitizerTest.java

Since the `name` is user provided it needs to be sanitized in all HTML views.
But in the side panel links the name can be used in its raw form without escaping.
For details see [JENKINS-61834](https://issues.jenkins.io/browse/JENKINS-61834).

[JENKINS-61834] Add a raw name for the results to be used as display name

---

plugin/pom.xml
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/BlamesModel.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/DetailsTableModel.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/ForensicsModel.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/IssuesModel.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/BlamesModelTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/ForensicsModelTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/IssuesModelTest.java

https://issues.jenkins.io/browse/JENKINS-64376
Description is added as a hidden column, so it can be searched, but doesn't clutter the view.
Downstream PR for https://github.com/jenkinsci/data-tables-api-plugin/pull/146

[JENKINS-64376] add issue description as hidden column for search

---

doc/Documentation.md
plugin/pom.xml
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/JobAction.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesPublisher.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/util/TrendChartType.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/JobActionITest.java

See [JENKINS-61196](https://issues.jenkins.io/browse/JENKINS-61196) for details

[JENKINS-61196] Add an additional trend chart option to show only the aggregation

---

plugin/pom.xml
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/Doxygen.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/ParsersITest.java

This is supposed to solve (at least partially) the issues described here: https://issues.jenkins.io/browse/JENKINS-64657.
The warnings that were not parsed were of this type:
```
Warning: doxygen no longer ships with the FreeSans font.
You may want to clear or change DOT_FONTNAME.
Otherwise you run the risk that the wrong font is being used for dot generated graphs.
Warning: source ../path/to/file is not a readable file or directory... skipping.
```
This modified Gcc4CompilerParser pattern catches these types.
This commit is related to jenkinsci/analysis-model#559

[JENKINS-64657] Use new DoxygenParser for Doxygen

---

plugin/pom.xml
plugin/src/main/java/io/jenkins/plugins/analysis/core/util/ModelValidation.java
plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/IssuesRecorder/help-trendChartType.html
plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/PublishIssuesStep/help-trendChartType.html
plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/RecordIssuesStep/help-trendChartType.html
plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/ScanForIssuesStep/help-trendChartType.html
plugin/src/main/resources/io/jenkins/plugins/analysis/core/util/Messages.properties
plugin/src/test/java/io/jenkins/plugins/analysis/core/util/ModelValidationTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/PyLintTest.java

While the steps support this new type the UI and help still lists only the old types. For details see [JENKINS-64830](https://issues.jenkins.io/browse/JENKINS-64830).

[JENKINS-64830] Add `AGGREGATION_ONLY` option in UI

---

etc/Jenkinsfile.analysis

this fixes the following error when trying to run jenkinsfile.analysis
```
Groovy.lang.MissingPropertyException: No such property: discoverGitReferenceBuild for class: groovy.lang.Binding
at groovy.lang.Binding.getVariable(Binding.java:63)
at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:270)
at org.kohsuke.groovy.sandbox.impl.Checker$7.call(Checker.java:353)
at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:357)
at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:333)
at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:333)
at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.getProperty(SandboxInvoker.java:29)
at …
```

fix No such property: discoverGitReferenceBuild 

---

plugin/pom.xml

Use last version of commons-beanutils as current one is subject to https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-0114
Signed-off-by: olivier lamy <olamy@apache.org>

Upgrade commons-beanutils 1.9.4

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/model/StaticAnalysisLabelProvider.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/Summary.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/SummaryTest.java

Preparation for fixing https://issues.jenkins.io/browse/JENKINS-65033
It's forwards and backwards compatible (no changes in the UI)
@uhafner

Use inline elements on run summary page

---

doc/Custom-Plugin.md

Without these, maven cannot find the parent pom. Thought I'd offer an update to the documentation to fix that problem.
- I have no desired changelog entry. I don't really care, just thought I'd help.
- I added the `<repository>` and `<pluginRepository>` sections required to get the provided pom to work.
- No issue, I just found it and fixed it.
- N/A
- Tests for a documentation change?

Add required repository sections to example pom

---

plugin/pom.xml
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/AnalysisModelParser.java

Accidently this method returned the private implementation `RegistryIssueDescriptionProvider`.

Let `getDescriptionProvider` return a `DescriptionProvider` instance

---

plugin/pom.xml
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/AnalysisResult.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/portlets/PullRequestMonitoringPortlet.java
plugin/src/main/resources/io/jenkins/plugins/analysis/core/portlets/Messages.properties
plugin/src/main/resources/io/jenkins/plugins/analysis/core/portlets/PullRequestMonitoringPortlet/monitor.jelly
plugin/src/main/resources/io/jenkins/plugins/analysis/core/portlets/PullRequestMonitoringPortlet/monitor.properties
plugin/src/main/webapp/js/issues-sunburst.js
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/StepsITest.java

Implement portlets for the https://github.com/jenkinsci/pull-request-monitoring-plugin.
Add one portlet for each analysis result which is added by the warnings-ng plugin to the actual run. Each portlet contains a sunburst diagram of fixed, outstanding and new issues. The new issues are clustered by severities, os it looks like this:

implement MonitorPortlet for pull-request-monitoring plugin

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/model/AnalysisResult.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/portlets/PullRequestMonitoringPortlet.java
plugin/src/main/resources/io/jenkins/plugins/analysis/core/portlets/PullRequestMonitoringPortlet/monitor.jelly
plugin/src/main/resources/io/jenkins/plugins/analysis/core/portlets/PullRequestMonitoringPortlet/monitor.properties
plugin/src/main/webapp/css/pull-request-portlet.css
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/StepsITest.java

Improved the display of portlets when no issues are present.
Before:
After:
1. No warnings at all
2. No new warnings but outstanding and probably some fixed: 
A sunburst diagram does not make any sense, because the sunburst diagram only shows the severity of the new issues as an interactive diagram together with the static outstanding and fixed ones (without severity clustering). So I decide to use the normal pie-chart for this use case.
3. New warnings, outstanding and fixed
Portlet remains the same as in #935 with the interactive sunburst diagram together with the severity cluster for new warnings.

make no-issues-portlet more expressive

---

plugin/src/main/resources/io/jenkins/plugins/analysis/warnings/groovy/GroovyScript/config.jelly

In the (freestyle) job configuration web form, the "Groovy Parser" form has two fields reporting jelly binding errors (highlighted in red boxes in the image below).
This seems to be caused by the underlying `Descriptor` class (`ReportScanningTool.ReportScanningToolDescriptor`) having the `@POST` annotation on the `doCheckReportEncoding` and `doCheckPattern` methods but the `config.jelly` file _for the Groovy Parser_ is missing the corresponding "use POST when calling Jenkins" notation for those two fields.
This change makes the "Groovy Parser" form use the same constructs used on the ReportScanningTool's form.

Fix Stapler "ERROR" for Groovy Parser job-configuration web-form

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/portlets/PullRequestMonitoringPortlet.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/util/QualityGateStatus.java
plugin/src/main/resources/io/jenkins/plugins/analysis/core/portlets/PullRequestMonitoringPortlet/monitor.jelly
plugin/src/test/java/io/jenkins/plugins/analysis/core/testutil/IntegrationTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/MiscIssuesRecorderITest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/QualityGateITest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/StepsITest.java

Internally the quality gate still uses the `BallColor` class to visualize the quality gate status. This class has not been adapted to use the new Jenkins status icons so it is required to use a different way to show the correct icon of the quality gate.
Screenshot

Use new status icons in quality gate of pull request portlet

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/AnalysisExecution.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/axivion/RemoteAxivionDashboard.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/steps/WarningChecksPublisherITest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/axivion/TestDashboard.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/ModuleDetectorITest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/ParsersITest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/tasks/TaskScannerTest.java

Usage of deprecated Gson / AspectJ APIs replaced and some cleanup.

Deprecated API usages replaced

---

plugin/src/main/resources/io/jenkins/plugins/analysis/warnings/charts.jelly

The `chartType` element used the same IDs as the other chart configuration dialogs (in the forensics API plugin).

Ensure that we use unique IDs in the UI

---

plugin/src/main/resources/index.jelly

Many searches on the plugin site now give no results because keywords like spotbugs or checkstyle are not included in description of any plugin. This PR aims to fix that, it should also improve search in plugin manager inside Jenkins.

Include keywords in plugin description

---

plugin/src/main/resources/io/jenkins/plugins/analysis/core/columns/IssuesTotalColumn/column.jelly

Followup for jenkinsci/jenkins#5763 in Jenkins 2.318. Tooltips now should use a different CSS class.

Update CSS of tooltips of issues column

---

plugin/src/main/java/io/jenkins/plugins/analysis/warnings/tasks/AgentScanner.java

Extract issues from file reports before attaching them to the aggregated report. Storing issues per file in a new report seems to be wasted memory.

Simplify structure of reports generated by open task scanner

---

plugin/pom.xml
plugin/src/main/resources/issues/property.jelly
ui-tests/src/main/java/io/jenkins/plugins/analysis/warnings/AbstractIssuesTable.java
ui-tests/src/main/java/io/jenkins/plugins/analysis/warnings/ScrollerUtil.java

Check if that still is required in recent versions of Jenkins.

Remove hiding of scroller

---

SUPPORTED-FORMATS.md
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/CppLint.java

Switch all occurrences of "C++ Lint" to Cpplint.
In the documentation, the tool is only mentioned by the name cpplint.
Source:
https://github.com/google/styleguide/tree/gh-pages/cpplint
https://pypi.org/project/cpplint
The corresponding PR in Ananlysis-model: [ PR #707](https://github.com/jenkinsci/analysis-model/pull/707)

Rename "C++ Lint" to Cpplint

---

plugin/src/main/java/io/jenkins/plugins/analysis/warnings/OwaspDependencyCheck.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/ParsersITest.java
plugin/src/test/resources/io/jenkins/plugins/analysis/warnings/steps/dependency-check-report.json

This PR is a continuation of https://github.com/jenkinsci/analysis-model/pull/708 and depends on https://github.com/jenkinsci/warnings-ng-plugin/pull/1115

Add OWASP dependency check issue parser

---

plugin/pom.xml
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/DetailFactory.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/InfoErrorDetail.java
plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/ResultAction/summary.jelly
plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/ResultAction/summary.properties
plugin/src/main/webapp/css/custom-style.css
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/DetailFactoryTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/InfoErrorDetailTest.java
ui-tests/src/main/java/io/jenkins/plugins/analysis/warnings/AnalysisSummary.java

Use the new messages dialog of the bootstrap plugin that has been introduced with jenkinsci/bootstrap5-api-plugin#65. Additionally use the new icon button introduced with jenkinsci/font-awesome-api-plugin#118. This new button uses the restyled tooltips that have been introduced in Jenkins 2.318 (jenkinsci/jenkins#5763).

Use new messages dialog and improve associated icon link 

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/model/DetailFactory.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/LabelProviderFactory.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/SummaryModel.java
plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/ResultAction/summary.jelly
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/DetailFactoryTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/SummaryModelTest.java

Additionally, show the number of warnings per tool in the summary.
See [JENKINS-67114](https://issues.jenkins.io/browse/JENKINS-67114) for details.

[JENKINS-67114] Remove link to tool result if number of warnings is 0

---

doc/Documentation.md
plugin/pom.xml
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/Tool.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/RegisteredParser.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/RegisteredParserTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/ParsersITest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/StepsITest.java

Otherwise we cannot replace the tool ID with a custom ID.

Rename the `id` parameter of `analysisModel` tool to `analysisModelId`

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/model/Tool.java

When a freestyle job has some pre-configured tools, then the `JenkinsFacade` instance will not be correctly instantiated.

[JENKINS-67307] Fix NPE during deserialization

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/model/StaticAnalysisLabelProvider.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/StaticAnalysisLabelProviderTest.java

Currently the description of an issue is not always shown. This depends on the actual parser used. 
See https://issues.jenkins.io/browse/JENKINS-67414

[JENKINS-67414] Do not ignore description of issue

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/AnalysisStepDescriptor.java

Currently the `recordIssues` step does not work in the Pipeline snippet generator. Since I do not see why the trend chart types should be restricted, I'm removing the permission check.
For details see [JENKINS-68336](https://issues.jenkins.io/browse/JENKINS-68336)

[JENKINS-68336] Check only for `READ` permissions when populating list models

---

plugin/src/main/java/io/jenkins/plugins/analysis/warnings/RegisteredParser.java
plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/ReportScanningTool/config.properties
plugin/src/main/resources/io/jenkins/plugins/analysis/core/util/Messages.properties
plugin/src/main/resources/io/jenkins/plugins/analysis/warnings/Messages.properties
plugin/src/main/resources/io/jenkins/plugins/analysis/warnings/RegisteredParser/local-config.jelly
plugin/src/main/resources/io/jenkins/plugins/analysis/warnings/RegisteredParser/local-config.properties
plugin/src/main/resources/io/jenkins/plugins/analysis/warnings/groovy/GroovyScript/config.properties
plugin/src/main/resources/io/jenkins/plugins/analysis/warnings/tasks/OpenTasks/config.properties
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/RegisteredParserTest.java
ui-tests/pom.xml
ui-tests/src/main/java/io/jenkins/plugins/analysis/warnings/IssuesRecorder.java
ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/SmokeTests.java
ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/UiTest.java

Selection of the parser of a registered analysis-model parser in the UI has been forgotten.

Add UI configuration of `analysisModelId`

---

plugin/pom.xml
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/BlamesModel.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/DetailsTableModel.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/ForensicsModel.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/IssuesModel.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/DuplicateCodeScanner.java
plugin/src/main/resources/issues/property.jelly
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/AbstractDetailsModelTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/BlamesModelTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/ForensicsModelTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/IssuesModelTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/DryTableModelTest.java
ui-tests/pom.xml
ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/ArchitectureTest.java

Using the width option does not work as expected so it makes more sense to let DataTables internal code decide which width should be used for each column. If the columns do not fit on the page then columns will be hidden according the specified `responsivePriority`.

Use responsive columns for all tables

---

plugin/pom.xml
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/DetailsTableModel.java

The age is shown as hyperlink, so all HTML tags need to be removed.

[JENKINS-68823] Use column type `HTML_NUMBER` for the age column

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/WarningChecksPublisher.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/steps/WarningChecksPublisherITest.java
plugin/src/test/resources/io/jenkins/plugins/analysis/core/steps/msbuild.log

When using ChecksPublisher to publish warnings generated by MsBuild, the annotations title is mostly empty (`-`) because MsBuild parser creates issues with only a `category` when it can't determine both the issue `category` and the issue `type`. 
So the real problem is that the MsBuild parser misuses the issue 'category' but I think changing it would be a brackig change (e.g. breaks issue filters) and only changing the 'visualization' is the 'safer' way. And eventually there are other parsers that have the same 'problem' and this way the user gets more information about the issue.

Use category if type is empty when publishing checks 

---

pom.xml
ui-tests/pom.xml

See https://github.com/jenkinsci/bom/pull/1384#discussion_r940755394.
When plugin compatibility tester (PCT) tests this plugin, it runs `mvn […] hpi:resolve-test-dependencies hpi:test-hpl surefire:test failsafe:integration-test failsafe:integration-test`, expecting all Jenkins plugins to have `hpi:resolve-test-dependencies` and `hpi:test-hpl` goals in all Maven modules. This plugin does not comply with the expectation, so PCT fails with:
> [ERROR] No plugin found for prefix 'hpi' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/basil/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
The parent POM layout of this plugin is highly non-standard and would benefit from being …

Support plugin compatibility tester (PCT)

---

ui-tests/pom.xml

Follows up #1327 by picking up https://github.com/jenkinsci/acceptance-test-harness/pull/885. Would appreciate a release. @basil @uhafner

Pick up `forkCount` fix from `acceptance-test-harness`

---

pom.xml
ui-tests/pom.xml

My latest run of PCT in https://ci.jenkins.io/job/Tools/job/bom/job/PR-1384/4/ failed with
```
[ERROR] Plugin org.jenkins-ci.tools:maven-hpi-plugin:3.33 or one of its dependencies could not be resolved: org.jenkins-ci.tools:maven-hpi-plugin:jar:3.33 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
org.apache.maven.plugin.PluginResolutionException: Plugin org.jenkins-ci.tools:maven-hpi-plugin:3.33 or one of its dependencies could not be resolved: org.jenkins-ci.tools:maven-hpi-plugin:jar:3.33 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached …
```

Add `pluginRepositories` for PCT

---

plugin/src/main/resources/io/jenkins/plugins/analysis/core/columns/IssuesTotalColumn/column.jelly

Updates the plugin to support the new tooltip framework introduced in core https://github.com/jenkinsci/jenkins/pull/6408
Images didn't seem to work for me locally hence the missing image.
---

Update for Tippy JS

---

ui-tests/pom.xml

Since 1.118 ATH switched to CD.
See https://github.com/jenkinsci/acceptance-test-harness/releases

Bump version of ATH to 5460

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/model/ResetQualityGateCommand.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/ResetQualityGateCommandTest.java

[JENKINS-70172](https://issues.jenkins.io/browse/JENKINS-70172)
Currently only users with the global configure right see and may click the "Reset quality gate" button.
Useres that may configure the job/build should also be able to reset the quality gate.

[JENKINS-70172] Use project configure permission for reset quality gate action

---

.gitignore
plugin/pom.xml
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/PluginArchitectureTest.java

Tests and hpi runtime was using different versions causing test compilation errors when running with PCT.
Related: https://github.com/jenkinsci/prism-api-plugin/pull/72

Align version of plugin-util-api plugin in test and compile dependencies

---

plugin/src/main/java/io/jenkins/plugins/analysis/warnings/axivion/AxivionSuite.java

ACL.SYSTEM can be safely replaced with null as the "authentication" argument. 
The credential api defaults to ACL.SYSTEM so Jenkins maintainers will need to replace the ACL.SYSTEM usages in the credential api. There are no ACL.SYSTEM2 equivalents yet.

Remove deprecated ACL.SYSTEM constant usage

---

plugin/pom.xml

When attempting to add this plugin to `jenkinsci/bom`, I received the following error when testing locally against the megawar:
```
[ERROR]   ConfigurationAsCodeITest.shouldCreateFreestyleJobUsingJobDsl:108->configureJenkins:134 » NoClassDefFound org/jenkinsci/plugins/configfiles/GlobalConfigFiles
[ERROR]   ConfigurationAsCodeITest.shouldFreestyleJobWithSpotBugsUsingJobDsl:69->configureJenkins:134 » NoClassDefFound org/jenkinsci/plugins/configfiles/GlobalConfigFiles
[ERROR]   ConfigurationAsCodeITest.shouldFreestyleJobWithTaskScannerUsingJobDsl:86->configureJenkins:134 » NoClassDefFound org/jenkinsci/plugins/configfiles/GlobalConfigFiles
[ERROR]   JobDslITest.shouldCreateFreestyleJobUsingJobDslAndVerifyIssueRecorderWithDefaultConfiguration:36->configureJenkins:126 » NoClassDefFound …
```

Allow plugin to be included in BOM

---

plugin/pom.xml
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/ReportScanningTool.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesPublisher.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesScanner.java

Avoids similar problems as described in  [JENKINS-70804](https://issues.jenkins.io/browse/JENKINS-70804).

Do not use format method when simply copying log messages

---

pom.xml

A future Maven multi-module aware version of PCT will require that every plugin has an `<scm>` section in its root `pom.xml` file. This PR proactively prepares this plugin to comply. The `child.scm.*.inherit.append.path` gibberish is part of the archetype and a standard practice in the Jenkins ecosystem for multi-module plugins to work around a surprising Maven behavior.

Add SCM section to `pom.xml`

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/WarningChecksPublisher.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/steps/WarningChecksPublisherITest.java

The checks of all other actions use a title without dot.

Remove dot from checks title

---

doc/Documentation.md

Functions cannot be called without brackets if they do not have any parameter. When copying the syntax from the documentation, it would not work for "discoverGitReferenceBuild"

Fix syntax for parameter-less function in documentation

---

plugin/pom.xml
plugin/src/main/java/io/jenkins/plugins/analysis/core/charts/HealthTrendChart.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/charts/NewVersusFixedPieChart.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/charts/NewVersusFixedTrendChart.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/charts/SeverityPalette.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/charts/SeverityPieChart.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/charts/SeverityTrendChart.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/charts/ToolsTrendChart.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/FileNameRenderer.java
plugin/src/main/resources/issues/property.jelly
plugin/src/main/resources/issues/severity-distribution.jelly
plugin/src/test/java/io/jenkins/plugins/analysis/core/charts/NewVersusFixedPieChartTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/charts/NewVersusFixedTrendChartTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/AbstractDetailsModelTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/FileNameRendererTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/DryTableModelTest.java

Use colors from the new Echarts `JenkinsPalette` for trend charts.
Downstream PR of https://github.com/jenkinsci/echarts-api-plugin/pull/287.

Make trend charts theme-aware

---

plugin/pom.xml
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/Grype.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/ParsersITest.java
plugin/src/test/resources/io/jenkins/plugins/analysis/warnings/steps/grype-report.json

Adding support for Grype scanner reports, see https://plugins.jenkins.io/grypescanner/ and https://github.com/anchore/grype.
This is a continuation of [analysis-model/pull/935 PR](https://github.com/jenkinsci/analysis-model/pull/935).

Add grype parser

---

plugin/src/main/java/io/jenkins/plugins/analysis/warnings/CrossCoreEmbeddedStudio.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/ParsersITest.java
plugin/src/test/resources/io/jenkins/plugins/analysis/warnings/steps/cces.log

This integrates https://github.com/jenkinsci/analysis-model/pull/937

Add parser for CCES (CrossCore Embedded Studio)

---

doc/Documentation.md
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/groovy/ParserConfiguration.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/groovy/ParserConfigurationTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/StepsITest.java

I have a Jenkins instance that multiple teams work on at the same time. Since it requires admin permissions to add a new parser via the UI, we allow users to add them via Groovy. However, the function `ParserConfiguration#setParsers` is much more prone to accidentally deleting all other parsers.
With this PR, single parsers can be added and deleted from within pipelines.
-> Unit Tests and tested in localhost instance
```[tasklist]
```

Add delete and add methods for parsers in global configuration

---

LICENSE
plugin/src/main/java/io/jenkins/plugins/analysis/core/filter/RegexpFilter.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/ReportScanningTool.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/Tool.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/ToolSelection.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/AnalysisStepDescriptor.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesRecorder.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/util/QualityGate.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/DuplicateCodeScanner.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/RegisteredParser.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/axivion/AxivionSuite.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/groovy/GroovyParser.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/groovy/GroovyScript.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/tasks/OpenTasks.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/filter/RegexpFilterTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/ToolSelectionDescriptorTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/util/QualityGateTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/RegisteredParserTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/groovy/GroovyParserTest.java

Additionally, use permissions for a `BuildableItem` in all validations.
See https://issues.jenkins.io/browse/JENKINS-72317 for details.

[JENKINS-72317] Use Jenkins.READ permission check for all list box models

---

plugin/pom.xml
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/PublishIssuesStep.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/RegisteredParser.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/RevApi.java

See https://github.com/uhafner/codingstyle/pull/861.

Remove suppress warnings: ctor rule has been disabled globally

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/model/DetailsTableModel.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/DetailsTableModelTest.java

Fixes [JENKINS-71435](https://issues.jenkins.io/browse/JENKINS-71435). Changed formatProperty() method in DetailsTableModel.java to display issues with blank categories as '-' category.
Before change:
After change:
```[tasklist]
```

[JENKINS-71435] Make empty properties clickable

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesScanner.java
plugin/src/main/resources/issues/scan-parameters.properties
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/ModuleDetectorITest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/PackageDetectorsITest.java

See [JENKINS-71492](https://issues.jenkins.io/browse/JENKINS-71492). Now the new property skips only the package and module detection but not the absolute path resolving.

[JENKINS-71492] Limit property `skipPostProcessing` to package and module detection.

---

plugin/src/main/webapp/css/custom-style.css
plugin/src/main/webapp/css/pull-request-portlet.css

Uses the Jenkins success colour variable rather than a hardcoded green.
**Before**
**After**
```[tasklist]
```

Use success colour variable rather than hardcoded colour

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/model/IssuesDetail.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/StaticAnalysisLabelProvider.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/AbstractDetailsModelTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/StaticAnalysisLabelProviderTest.java

The age link should be plain text if the build has been deleted.

[JENKINS-65845] Don't link to deleted builds

---

plugin/src/main/webapp/css/custom-style.css

After https://github.com/jenkinsci/font-awesome-api-plugin/releases/tag/v6.5.1-2 the icon color changed to gray.

Make the no-issues icon green again

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/model/ReportXmlStream.java

Now the correct class is restored.

Fix `LineRange` serialization alias

---

plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/FixedWarningsDetail/index.jelly
plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/IssuesDetail/filled.jelly
plugin/src/main/resources/issues/property.jelly

DataTables 2.0.0 brings some new layout elements that require some UI adjustments.

Prepare layout for DataTables 2.0.0

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/model/SummaryModel.java
plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/ResultAction/summary.jelly
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/SummaryModelTest.java

UI visualization of the link is broken again in Jenkins core: [JENKINS-72491](https://issues.jenkins.io/browse/JENKINS-72491). So it makes sense to remove the status icon and only show the raw link. When a fix for https://github.com/jenkinsci/jenkins/pull/8705 is available, we can revert that change.

Remove icon from reference link as it is broken in core again

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/model/PropertyStatistics.java
plugin/src/main/resources/issues/property.jelly
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/PropertyStatisticsTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/ModuleDetectorITest.java

Otherwise the hyperlink is not clickable.

Replace empty property with "-"

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/ScanForIssuesStep.java

Restore the getter for the deprecated setter. 
See https://issues.jenkins.io/browse/JENKINS-72059.

[JENKINS-72059] Add missing deprecated getter

---

plugin/src/main/resources/io/jenkins/plugins/analysis/core/columns/IssuesTotalColumn/column.jelly

Adds `data` attribute used by `sortable.js`. Since `data` is always a number this guarantees sorting by number of issues will work as expected. Without this change, if one or more entries are missing in the column, alphabetical sort is used 
2 > 12 > 1 > 0 > -
Also removes 2 lines of inline JS that is no longer needed, improving CSP compatibility.
Code introduced in https://github.com/jenkinsci/warnings-ng-plugin/commit/0a5457e8, made redundant in https://github.com/jenkinsci/warnings-ng-plugin/pull/1379.
Manually checked that the column sorting works on my Jenkins instance and tooltip functionality is still OK.
```[tasklist]
```

Correct sorting by issues column when some entries are missing

---

plugin/pom.xml

PMD 7.x fails with an IllegalStateException:
````
<![CDATA[org.apache.commons.lang3.exception.ContextedRuntimeException: java.lang.IllegalStateException: Disambiguation pass should resolve everything except qualified ctor calls
Exception Context:
[1:Resolving type of=!debug only! [ClassType:105:43]SymbolIconLabelProvider]
---------------------------------
at net.sourceforge.pmd.util.AssertionUtil.contexted(AssertionUtil.java:236)
at net.sourceforge.pmd.lang.java.ast.AbstractJavaTypeNode.getTypeMirror(AbstractJavaTypeNode.java:54)
at net.sourceforge.pmd.lang.java.ast.ASTClassType.getTypeMirror(ASTClassType.java:37)
at net.sourceforge.pmd.lang.java.ast.AbstractJavaTypeNode.getTypeMirror(AbstractJavaTypeNode.java:39)
at net.sourceforge.pmd.lang.java.ast.ASTClassType.getTypeMirror(ASTClassType …
```

Exclude DuplicateCodeScanner.java from PMD analysis

---

plugin/pom.xml
plugin/src/main/java/io/jenkins/plugins/analysis/core/columns/IssuesTotalColumn.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/integrations/JobDslITest.java
plugin/src/test/resources/io/jenkins/plugins/analysis/warnings/integrations/column-dsl.yaml

Otherwise the column cannot be used in JobDSL configuration files.

Add missing symbol for the issue-totals column

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesScanner.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/RecordIssuesStep.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/StepsOnAgentITest.java

- Fix the `recordIssues` step to correctly honor the `sourceCodeRetention` parameter.
- Added a test to verify that source code is not copied when sourceCodeRetention: 'NEVER'` is set.

[JENKINS-73164] Fix record issues step ignores source code retention parameter

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesRecorder.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/PublishIssuesStep.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/RecordIssuesStep.java
plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/IssuesRecorder/help-skipDeltaCalculation.html
plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/PublishIssuesStep/help-skipDeltaCalculation.html
plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/RecordIssuesStep/help-skipDeltaCalculation.html
plugin/src/main/resources/issues/publish-parameters.jelly
plugin/src/main/resources/issues/publish-parameters.properties
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/GitForensicsITest.java

See [JENKINS-72973](https://issues.jenkins.io/browse/JENKINS-72973) for details.

[JENKINS-72973] Add an option to skip the SCM delta calculation

---

plugin/pom.xml
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/YoctoScanner.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/ParsersITest.java
plugin/src/test/resources/io/jenkins/plugins/analysis/warnings/steps/yocto_scanner_result.json

Yocto project support CVE security vulnerabilities using cve-check in the specific image or target you are building, add the following setting to your configuration:
INHERIT += "cve-check"
status of each CVE: Patched, Unpatched or Ignored
The scanner look only for Unpatched package and calculate the severity using the score_v2 or score_v3
Cloned https://github.com/uhafner/warnings-ng-plugin-devenv.git
Apply this patch and the pull request of new Yocto Parser
Deploy on personal jenkins installation

Adding Yocto Scanner support.

---

plugin/pom.xml
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/groovy/GroovyExpressionMatcher.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/steps/WarningChecksPublisherITest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/integrations/TimeStamperPluginITest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/integrations/TokenMacroITest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/QualityGateITest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/StepsITest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/StepsOnAgentITest.java
ui-tests/src/main/java/io/jenkins/plugins/analysis/warnings/AbstractIssuesTable.java

See [JENKINS-73776](https://issues.jenkins.io/browse/JENKINS-73776).

Use new Jenkins baseline 2.462

---

plugin/pom.xml

Since the plugin bill of materials includes those plugin versions, let's use them in the test configuration rather than declaring them explicitly and then maintaining them with dependabot updates.
Should not change the runtime dependencies in any way, since they are purely test dependencies.
Supersedes:
* https://github.com/jenkinsci/warnings-ng-plugin/pull/1828
Confirmed that automated tests pass in the plugin module that includes the change.

Test with job-dsl and maven plugin versions from BOM

---

plugin/pom.xml

Current checks-api does not require the exclusion
Confirmed that spotbugs-annotations is not included in the plugin packaging.

Remove unused exclusion of spotbugs-annotations from checks-api

---

SUPPORTED-FORMATS.md

Without the equals sign, I got the following error using PHPStan v1.12.4:
```
The "--error-format checkstyle" option does not exist.  
analyse [-c|--configuration CONFIGURATION] [-l|--level LEVEL] [--no-progress] [--debug] [-a|--autoload-file AUTOLOAD-FILE] [--error-format ERROR-FORMAT] [-b|--generate-baseline [GENERATE-BASELINE]] [--allow-empty-baseline] [--memory-limit MEMORY-LIMIT] [--xdebug] [--fix] [--watch] [--pro] [--fail-without-result-cache] [--] [<paths>...]
```

Correct CLI argument hint for PHPStan

---

plugin/src/main/resources/io/jenkins/plugins/analysis/core/portlets/IssuesChartPortlet/portlet.jelly
plugin/src/main/resources/io/jenkins/plugins/analysis/core/portlets/IssuesChartPortlet/render-trend-chart.js

https://issues.jenkins.io/browse/JENKINS-73894
Makes the plugin a step closer to being CSP compatible.
I've installed https://plugins.jenkins.io/dashboard-view/ plugin so that I can reach the code in question. Created a new dashboard view, and in Portlets at the top of the page section I've added Static analysis issues chart. I've not spent time setting up a project that would have actual violations, so my issues chart is empty.
https://www.loom.com/share/9ed2252e9eda40e4a17e8e745757fe18?sid=e90705e4-c41c-4b35-9a20-0bf361676310
https://www.loom.com/share/7a2a6a2cab2d428f8aa8a3af873174a0?sid=8cee3380-af6b-44eb-aff7-a352d126c549

[JENKINS-73894] Un-inline JavaScript in IssuesChartPortlet/portlet.jelly

---

plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/ResultAction/bind-reset-button.js
plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/ResultAction/summary.jelly

[JENKINS-73896](https://issues.jenkins.io/browse/JENKINS-73896)
Tested against a sample project that intentionally has code violations (https://github.com/yaroslavafenkin/bad-project). In job config I've added Record compiler warnings and static analysis results post-build action, added PMD and Checkstyle static analysis tools. In advanced section I've added a quality gate and set the threshold to 3.
https://www.loom.com/share/423b4f0b70584ca5b8bf2f912dc5f849?sid=e77eb4c4-969a-42ee-8e12-df9ebdba0687
https://www.loom.com/share/0294d526ad0e439fafc7106e271716d6?sid=0d659442-3a37-4579-b49b-9a0c83b19f5b
CSP violations that still appear in the "after" video are then ones that are fixed by https://github.com/jenkinsci/echarts-api-plugin/pull/357.

[JENKINS-73896] Un-inline JavaScript in ResultAction/summary.jelly

---

plugin/src/main/resources/io/jenkins/plugins/analysis/core/portlets/PullRequestMonitoringPortlet/monitor.jelly

https://issues.jenkins.io/browse/JENKINS-73959
Requires https://plugins.jenkins.io/pull-request-monitoring/ to be installed. I've set up a multibranch project, because that's the only supported project type according to https://plugins.jenkins.io/pull-request-monitoring/#plugin-content-prerequisites.
Also used https://plugins.jenkins.io/github-branch-source/ as branch source for the project. Repo I've used as the source is https://github.com/yaroslavafenkin/bad-project.
[Before the change](https://youtu.be/-XQBPM_w5p4?si=CeVZafCJHP847o42)
[After the change](https://youtu.be/bc_oqckfgWk?si=dIypmh5hx6IyNve0)
Other CSP violations that appear in the video come from https://github.com/jenkinsci/pull-request-monitoring-plugin/blob/d602c91131a8112eef8cc9d00aee013f4443a307/src/main/resources/io/je …

[JENKINS-73959] Use CSP compatible version of `st:bind` in `PullRequestMonitoringPortlet/monitor.jelly`

---

plugin/src/main/java/io/jenkins/plugins/analysis/warnings/Valgrind.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/ParsersITest.java
plugin/src/test/resources/io/jenkins/plugins/analysis/warnings/steps/valgrind.xml

Allow to use valgrindParser to report memory issues
The analytic-model already has the valgrind model. Just extend the plugin to use it.
recordIssues sourceCodeRetention: 'LAST_BUILD',
tool: Valgrind(pattern: "out/test/memcheck.xml"),
qualityGates: [[threshold: 1, type: 'TOTAL', criticality: 'FAILURE']]
Deploy locally on latest jenkins instance version 2.489

Adding Valgrind Issues reporting

---

plugin/pom.xml
plugin/src/main/java/io/jenkins/plugins/analysis/core/columns/IssuesTotalColumn.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/IssueReportScanner.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/ResultAction.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/StaticAnalysisLabelProvider.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/Tool.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/SpotBugs.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/axivion/AxivionSuite.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/groovy/DynamicDocumentParser.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/groovy/DynamicLineParser.java

Use new API methods of analysis-model 13.0.0.

Use new Java 17 based API of analysis-model

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/model/DeltaReport.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/IconLabelProvider.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/LabelProviderFactory.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/ReportScanningTool.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/ResultAction.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/StaticAnalysisLabelProvider.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/SvgIconLabelProvider.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/AnnotatedReport.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/tasks/OpenTasks.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/IconLabelProviderTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/testutil/WarningsIntegrationTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/MiscIssuesRecorderITest.java

See [JENKINS-72777](https://issues.jenkins.io/browse/JENKINS-72777).

[JENKINS-72777] Use icon of configured parser even when ID is overwritten by the user

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/model/IssuesDetail.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/JobAction.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/JobActionTest.java

Migrate from deprecated functionality to non-deprecated equivalents.

Migrate from EE 8 to EE 9

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/model/ReportScanningTool.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesScanner.java
plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/ReportScanningTool/config.jelly
plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/ReportScanningTool/config.properties
plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/ReportScanningTool/help-linesLookAhead.html
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/AffectedFilesResolverITest.java
plugin/src/test/resources/io/jenkins/plugins/analysis/warnings/steps/affected-files/FingerprintTestWithModification.java
plugin/src/test/resources/io/jenkins/plugins/analysis/warnings/steps/affected-files/FingerprintTestWithoutModification.java
plugin/src/test/resources/io/jenkins/plugins/analysis/warnings/steps/affected-files/javalog-1.txt
plugin/src/test/resources/io/jenkins/plugins/analysis/warnings/steps/affected-files/javalog-2.txt

This PR introduces a tool-based configuration for setting the context lines considered during the fingerprinting process in FullTextFingerprint.
See :
https://issues.jenkins.io/browse/JENKINS-61607
https://github.com/jenkinsci/analysis-model/pull/1136
https://github.com/jenkinsci/analysis-model-api-plugin/pull/184
(https://github.com/jenkinsci/warnings-ng-plugin/pull/1943)

Add methods to configure context lines for fingerprinting 

---

plugin/src/main/java/io/jenkins/plugins/analysis/warnings/groovy/GroovyParser.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/groovy/GroovyParserTest.java

\R matches _any_ unicode newline sequence, and may appear in custom groovy parsers besides the usual \r and \n.
None. Currently sitting behind a company proxy that prohibits the Maven build to download all dependencies. If you need specific tests, I would have to rework this from a private machine.

Recognize `\R` for multiline regex in groovy parsers

---

.github/workflows/ui-tests.yml
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/ResultAction.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesRecorder.java
plugin/src/main/webapp/js/issues-sunburst.js
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/StepsITest.java
ui-tests/src/main/java/io/jenkins/plugins/analysis/warnings/AnalysisResult.java
ui-tests/src/main/java/io/jenkins/plugins/analysis/warnings/AnalysisSummary.java
ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/DetailsTabUiTest.java
ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/SmokeTests.java
ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/UiTest.java
ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/WarningsPluginUiTest.java

In https://github.com/jenkinsci/warnings-ng-plugin/pull/1919 a new icon property has been added to the recorder. This accidentally broke the URL mapping of the warning results.
When a custom ID is given, then this ID will be used as URL. Only for empty URLs, the default ID of the label provider will be used.
Additionally, the log messages have been fixed when the ID is used in tool and recorder (see JENKINS-75391).

[JENKINS-75344] Fix custom URL name of result action

---

plugin/pom.xml
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/JobAction.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/ResultAction.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/JobActionTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/JobActionITest.java
ui-tests/src/main/java/io/jenkins/plugins/analysis/warnings/IssuesRecorder.java
ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/TrendChartsUiTest.java

Use the ID of the result action when creating a project action. This is a followup to
https://github.com/jenkinsci/warnings-ng-plugin/pull/1970

[JENKINS-75394] Use custom ID and icon in project action

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/model/AnalysisBuildsFallback.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/MissingResultFallbackHandler.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/JobActionITest.java

This PR introduces an extension which helps to display job links and charts even if latest builds does not contain results.
See: [Issue](https://issues.jenkins.io/browse/JENKINS-57636)

Display Project Actions from previous builds when missing in latest build

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/model/AnalysisResult.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/ResultAction.java

The [fix for JENKINS-72777](https://issues.jenkins.io/browse/JENKINS-72777) requires to store the original ID of a parser, so that we can show the correct name, label, and ID in the UI even when the user changed some of these properties.
This caused [JENKINS-75438](https://issues.jenkins.io/browse/JENKINS-75438) because now all issues are read from the XML to get this ID. This causes severe performance issues for jobs that have large reports with a lot of issues. 
It will improve the performance if the ID of the parser is stored in the `AnalysisResult` which is deserialized from XML anyway.

[JENKINS-75438] Store parser ID directly in `AnalysisResult`

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/model/MissingResultFallbackHandler.java

It is sufficient to return the found project actions. The previously created transient action does not make sense.

[JENKINS-75935][JENKINS-75748] Remove duplicate transient actions

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/columns/IssuesTotalColumn.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/columns/WarningsAppearanceConfiguration.java
plugin/src/main/resources/io/jenkins/plugins/analysis/core/columns/Messages.properties
plugin/src/main/resources/io/jenkins/plugins/analysis/core/columns/WarningsAppearanceConfiguration/config.jelly
plugin/src/main/resources/io/jenkins/plugins/analysis/core/columns/WarningsAppearanceConfiguration/config.properties
plugin/src/main/resources/io/jenkins/plugins/analysis/core/columns/WarningsAppearanceConfiguration/help-defaultName.html
plugin/src/main/resources/io/jenkins/plugins/analysis/core/columns/WarningsAppearanceConfiguration/help-defaultType.html
plugin/src/main/resources/io/jenkins/plugins/analysis/core/columns/WarningsAppearanceConfiguration/help-enableColumnByDefault.html
plugin/src/test/java/io/jenkins/plugins/analysis/core/columns/IssuesTotalColumnTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/columns/WarningsAppearanceConfigurationTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/integrations/JobDslITest.java
plugin/src/test/resources/io/jenkins/plugins/analysis/warnings/integrations/column.yaml
ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/IssuesColumnUiTest.java

The new appearance configuration for the warnings column should also provide a way to specify the default warnings type and column name.

Add additional configuration options for the warnings column

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/AnnotatedReport.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesRecorder.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/PublishIssuesStep.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/StepsITest.java

When logging the messages of reports, then make sure that all messages appear only once.

[JENKINS-75764] Skip already shown log messages in console log

---

pom.xml

During a release, the quick-build profile is active. So no tests and analysis is started.

Ignore UI tests during release

---

plugin/pom.xml
plugin/src/test/java/io/jenkins/plugins/archunit/PluginArchitectureTest.java

Bump the version of plugin-util to 6.1165.v322e76215b_a_4. This version contains the missing class again.

[JENKINS-76020] Resolve missing architecture rules
