jenkinsci/warnings-ng-plugin

doc/Documentation.md

PR for https://issues.jenkins-ci.org/browse/JENKINS-56078

Fixed pmdparser in documentation

---

src/main/java/io/jenkins/plugins/analysis/core/model/FilesScanner.java
src/main/java/io/jenkins/plugins/analysis/core/model/ReportScanningTool.java
src/main/java/io/jenkins/plugins/analysis/core/util/FileFinder.java
src/main/resources/io/jenkins/plugins/analysis/core/model/ReportScanningTool/config.jelly
src/main/resources/io/jenkins/plugins/analysis/core/model/ReportScanningTool/config.properties
src/test/java/io/jenkins/plugins/analysis/core/testutil/IntegrationTest.java
src/test/java/io/jenkins/plugins/analysis/warnings/recorder/FilesScannerITest.java
src/test/resources/io/jenkins/plugins/analysis/warnings/recorder/files-scanner/symlinks/actual_files/checkstyle.xml
src/test/resources/io/jenkins/plugins/analysis/warnings/recorder/files-scanner/symlinks/actual_files/nonFilePatternMatch.txt

It defaults to enabled, so that existing users shouldn't have any behaviour change when upgrading the plugin.

[JENKINS-56065] Add a checkbox to control the traversal of symlinks.

---

src/test/java/io/jenkins/plugins/analysis/core/scm/GitCheckerTest.java

Unit Tests for GitChecker (JENKINS-56720)

---

src/test/java/io/jenkins/plugins/analysis/core/charts/NewVersusFixedSeriesBuilderTest.java

This PullRequest isn't complete yet. Could not add the "work in progress" label.

Unit tests for NewVersusFixedSeriesBuilder (JENKINS-56713)

---

src/test/java/io/jenkins/plugins/analysis/core/charts/CompositeResultTest.java

This PullRequest isn't complete yet.
Just to check if everything works properly.

Added unit tests for CompositeResult class

---

src/test/java/io/jenkins/plugins/analysis/core/testutil/IntegrationTest.java
src/test/java/io/jenkins/plugins/analysis/warnings/recorder/SourceControlTableITest.java
src/test/java/io/jenkins/plugins/analysis/warnings/recorder/pageobj/SourceControlRow.java
src/test/java/io/jenkins/plugins/analysis/warnings/recorder/pageobj/SourceControlTable.java

Page Objects and integration tests for the sourcecontrol-table in the build overview.

SourceControlTable page objects & integration tests

---

src/test/java/io/jenkins/plugins/analysis/warnings/DumbSlaveITest.java

Reproducing JENKINS-56007 does not work with this integration test.

JENKINS-56007

---

src/test/java/io/jenkins/plugins/analysis/core/columns/IssueCounterITest.java
src/test/resources/io/jenkins/plugins/analysis/core/columns/javac_10_warnings.txt
src/test/resources/io/jenkins/plugins/analysis/core/columns/javac_1_warning.txt
src/test/resources/io/jenkins/plugins/analysis/core/columns/javac_python_3_issues.txt

This test implements an integration test for the issue counter in the core jenkins column.

Create Issue counter Integration Test

---

pom.xml
src/test/java/io/jenkins/plugins/analysis/warnings/FolderITest.java
src/test/java/io/jenkins/plugins/analysis/warnings/recorder/pageobj/SummaryBox.java
src/test/resources/io/jenkins/plugins/analysis/warnings/javac-second-build.txt

* Add jenkins folder plugins for tests
* Add tests for double and single folder structures
* Individual folder names

folder-plugin Integrationtests

---

pom.xml

https://www.joda.org/joda-time/changes-report.html

update joda-time from 2.9.5 to 2.9.9

---

pom.xml
src/test/java/io/jenkins/plugins/analysis/core/model/ForensicsModelTest.java

Migrate long days to int days.

Bump version of forensics-api to 0.3.0-SNAPSHOT.

---

src/test/java/io/jenkins/plugins/analysis/core/scm/GitBlamerITest.java
src/test/java/io/jenkins/plugins/analysis/warnings/recorder/AffectedFilesResolverITest.java
src/test/java/io/jenkins/plugins/analysis/warnings/recorder/MiscIssuesRecorderITest.java
src/test/java/io/jenkins/plugins/analysis/warnings/recorder/pageobj/BlamesRow.java
src/test/java/io/jenkins/plugins/analysis/warnings/recorder/pageobj/IssueRow.java
src/test/java/io/jenkins/plugins/analysis/warnings/recorder/pageobj/TableRow.java

Add a parent class for all row models.

Generalize table row models

---

pom.xml

Upgrade com.fasterxml.jackson.core:jackson-databind to latest version 2.9.10.

Bump version of jackson-databind to 2.9.10

---

doc/Documentation.md

Attribute is called `size` and not  `threshold`.

Fix remote API result attribute name in documentation

---

src/main/java/io/jenkins/plugins/analysis/warnings/axivion/AxIssueKind.java
src/main/java/io/jenkins/plugins/analysis/warnings/axivion/AxRawIssue.java
src/main/java/io/jenkins/plugins/analysis/warnings/axivion/AxivionDashboard.java
src/main/java/io/jenkins/plugins/analysis/warnings/axivion/AxivionParser.java
src/main/java/io/jenkins/plugins/analysis/warnings/axivion/AxivionSuite.java
src/main/java/io/jenkins/plugins/analysis/warnings/axivion/DefaultTransformations.java
src/main/java/io/jenkins/plugins/analysis/warnings/axivion/RemoteAxivionDashboard.java
src/main/resources/io/jenkins/plugins/analysis/warnings/axivion/AxivionSuite/config.properties
src/test/java/io/jenkins/plugins/analysis/warnings/axivion/TestDashboard.java

Replace json parsing in Axivion Suite library to make use of streaming, improving the performance

Improve performance of Axivion Suite

---

pom.xml
src/main/java/io/jenkins/plugins/analysis/core/model/AnalysisResult.java
src/main/java/io/jenkins/plugins/analysis/core/model/ResultAction.java
src/main/java/io/jenkins/plugins/analysis/core/steps/AnnotatedReport.java
src/main/java/io/jenkins/plugins/analysis/core/util/IssuesStatistics.java
src/main/java/io/jenkins/plugins/analysis/core/util/QualityGateStatus.java
src/main/java/io/jenkins/plugins/analysis/core/util/StaticAnalysisRun.java
src/test/java/io/jenkins/plugins/analysis/core/testutil/IntegrationTest.java
src/test/java/io/jenkins/plugins/analysis/warnings/StepsITest.java

See [JENKINS-57566 ](https://issues.jenkins-ci.org/browse/JENKINS-57566) for details.

[JENKINS-57566] Add whitelisting of several step result methods

---

pom.xml
src/main/java/io/jenkins/plugins/analysis/core/restapi/IssueApi.java
src/main/java/io/jenkins/plugins/analysis/core/restapi/ReportApi.java
src/main/java/io/jenkins/plugins/analysis/core/steps/AnnotatedReport.java
src/test/java/io/jenkins/plugins/analysis/warnings/StepsITest.java
src/test/java/io/jenkins/plugins/analysis/warnings/recorder/RemoteApiITest.java
src/test/resources/design.puml
src/test/resources/io/jenkins/plugins/analysis/warnings/recorder/rest-api/all-issues.xml
src/test/resources/io/jenkins/plugins/analysis/warnings/recorder/rest-api/fixed-issues.xml
src/test/resources/io/jenkins/plugins/analysis/warnings/recorder/rest-api/issues.xml
src/test/resources/io/jenkins/plugins/analysis/warnings/recorder/rest-api/new-issues.xml
src/test/resources/io/jenkins/plugins/analysis/warnings/recorder/rest-api/outstanding-issues.xml

See discussion in https://gitter.im/jenkinsci/warnings-plugin?at=5e4ec032c2c73b70a449aeea.

Add whitelisted method that returns the issues of a report

---

src/main/java/io/jenkins/plugins/analysis/core/columns/IssuesTotalColumn.java
src/main/java/io/jenkins/plugins/analysis/core/util/IssuesStatistics.java
src/test/java/io/jenkins/plugins/analysis/core/columns/IssuesTotalColumnTest.java
src/test/java/io/jenkins/plugins/analysis/core/testutil/JobStubs.java

See [JENKINS-59592](https://issues.jenkins-ci.org/browse/JENKINS-59592?jql=component%20%3D%20warnings-ng-plugin%20AND%20labels%20%3D%20newbie-friendly)

[JENKINS-59592] Link issue column to selected type

---

plugin/pom.xml
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/recorder/DockerContainerITest.java

Bump version of analysis-pom to 4.0.0

---

doc/Documentation.md

Fix source code links

---

plugin/pom.xml
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/recorder/MiscIssuesRecorderITest.java

JENKINS-62102: Remove UI assertions from MiscIssueRecorderITest

---

plugin/src/test/java/io/jenkins/plugins/analysis/warnings/TaskScannerITest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/tasks/TaskScannerTest.java
plugin/src/test/resources/io/jenkins/plugins/analysis/warnings/tasks/checkstyle-with-windows-encoding.txt
plugin/src/test/resources/io/jenkins/plugins/analysis/warnings/tasks/file-with-strange-characters.txt

Co-authored-by: DieAkuteSense <10849187+dieakutesense@users.noreply.github.com>

JENKINS-62110 Add integration tests for task scanner

---

plugin/pom.xml
ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/SmokeTests.java
ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/UiTest.java

Extend Smoke Tests with dashboard view assertions

---

ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/SmokeTests.java

Add IssuesColumn assertions to SmokeTests

---

ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/SmokeTests.java

Co-authored-by: DaAnda97 <andreas.riepl@gmx.net>

Add IssuesColumn Assertion to SmokeTests

---

ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/SmokeTests.java

 Add details tab UI assertions to SmokeTests

---

ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/SmokeTests.java

Add detailstab UI tests to SmokeTests

---

ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/SmokeTests.java
ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/UiTest.java

Add trendchart-ui-tests to smoke tests

add trendchartTest to smokeTests

---

plugin/pom.xml
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/PluginArchitectureTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/tasks/TaskScannerBenchmark.java

Add benchmark tests for tasks scanner

---

plugin/src/main/java/io/jenkins/plugins/analysis/warnings/Flawfinder.java
plugin/src/main/resources/io/jenkins/plugins/analysis/warnings/Messages.properties
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/ParsersITest.java
plugin/src/test/resources/io/jenkins/plugins/analysis/warnings/steps/flawfinder.log

This fully adds the Flawfinder parser as a plugin.

Add Flawfinder analysis plugin

---

plugin/pom.xml
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesRecorder.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/PublishIssuesStep.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/WarningChecksPublisher.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/steps/WarningChecksPublisherITest.java

Bump version of checks-api to 0.2.2

---

plugin/src/test/java/io/jenkins/plugins/analysis/core/steps/MatrixBridgeTest.java

fixes: JENKINS-59603
Had a little trouble stubbing the chained function calls. Got a way around it. Happy to take remarks :smiley_cat:

Unittest for MatrixBridge

---

plugin/pom.xml
plugin/src/main/java/io/jenkins/plugins/analysis/core/filter/IncludeType.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/filter/RegexpFilter.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/ReportScanningTool.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/Tool.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/ToolSelection.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/AnalysisStepDescriptor.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesRecorder.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/axivion/AxivionSuite.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/groovy/GroovyParser.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/tasks/OpenTasks.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/filter/RegexpFilterTest.java

Downstream PR for https://github.com/jenkinsci/plugin-util-api-plugin/pull/68.

Also check for permissions in `check` methods

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/model/IssuesDetail.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/PropertyStatistics.java
plugin/src/main/resources/issues/property.jelly
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/PropertyStatisticsTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/pageobj/PropertyTable.java
ui-tests/src/main/java/io/jenkins/plugins/analysis/warnings/AnalysisResult.java
ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/UiTest.java

This implements https://issues.jenkins.io/browse/JENKINS-62416

[JENKINS-62416] Add column for new warnings in properties table

---

plugin/src/main/java/io/jenkins/plugins/analysis/warnings/tasks/TaskScanner.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/tasks/TaskScannerTest.java

See: https://issues.jenkins-ci.org/browse/JENKINS-64622

[JENKINS-64622] - Gracefully handles patterns that contain optional groups

---

plugin/pom.xml
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesRecorder.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesScanner.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/RecordIssuesStep.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/ScanForIssuesStep.java
plugin/src/main/resources/issues/scan-parameters.jelly
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/ReferenceFinderITest.java
ui-tests/src/main/java/io/jenkins/plugins/analysis/warnings/IssuesRecorder.java
ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/FreeStyleConfigurationUiTest.java

Downstream PR for https://github.com/jenkinsci/forensics-api-plugin/pull/246

Select blamer for a specific SCM

---

plugin/pom.xml

Reverts jenkinsci/warnings-ng-plugin#752

Revert "Bump git from 4.4.5 to 4.5.2"

---

plugin/src/main/java/io/jenkins/plugins/analysis/warnings/groovy/GroovyParser.java
plugin/src/main/resources/io/jenkins/plugins/analysis/warnings/groovy/GroovyParser/config.jelly
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/groovy/GroovyParserTest.java

See discussion in [Gitter](https://gitter.im/jenkinsci/warnings-plugin?at=60132e579d5c644f66368270).

Show validation error message if parser is not valid

---

ui-tests/pom.xml

Bump JUT to 2.263.3 and run ATH tests with chrome-container

---

plugin/pom.xml
plugin/src/main/java/io/jenkins/plugins/analysis/core/filter/RegexpFilter.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/ReportScanningTool.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/Tool.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/ToolSelection.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/AnalysisStepDescriptor.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesRecorder.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/util/ModelValidation.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/util/QualityGate.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/DuplicateCodeScanner.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/axivion/AxivionSuite.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/tasks/OpenTasks.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/filter/RegexpFilterTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/ToolSelectionDescriptorTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/util/QualityGateTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/PluginArchitectureTest.java

See [JENKINS-64627](https://issues.jenkins.io/browse/JENKINS-64627) for details.

[JENKINS-64627] Use CONFIGURE permission of specific job if possible

---

plugin/src/main/java/io/jenkins/plugins/analysis/warnings/groovy/GroovyScript.java

Followup to https://github.com/jenkinsci/warnings-ng-plugin/pull/801

Fix permissions for Groovy parser selection

---

plugin/pom.xml
plugin/src/main/java/io/jenkins/plugins/analysis/core/charts/SeverityPalette.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/ReportXmlStream.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/SourcePrinter.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/util/IssuesStatistics.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/util/LocalizedSeverity.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/PmdMessages.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/PyLint.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/axivion/DefaultTransformations.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/axivion/RemoteAxivionDashboard.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/groovy/GroovyParser.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/groovy/ParserConfiguration.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/DeltaReportTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/PropertyStatisticsTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/ReportXmlStreamTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/StaticAnalysisToolSuiteTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/steps/MatrixBridgeTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/groovy/DynamicDocumentParserTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/AffectedFilesResolverITest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/DryITest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/MiscIssuesRecorderITest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/ParsersITest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/StepsOnAgentITest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/tasks/TaskScannerBenchmark.java
ui-tests/pom.xml
ui-tests/src/main/java/io/jenkins/plugins/analysis/warnings/IssuesColumnConfiguration.java
ui-tests/src/main/java/io/jenkins/plugins/analysis/warnings/IssuesDetailsTable.java
ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/IssuesColumnUiTest.java

Requires new Jenkins Baseline 2.249.1

[JENKINS-62963] Bump version of analysis-pom to to 5.0.0

---

plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/ResultAction/summary.jelly

I noticed it included many times on the run summary view

Only include css file once

---

doc/Documentation.md
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/FilesScanner.java
plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/WarningsPluginConfiguration/help-sourceDirectories.html
plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/IssuesRecorder/help-sourceDirectory.html
plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/PublishIssuesStep/help-referenceJobName.html
plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/PublishIssuesStep/help-sourceDirectory.html
plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/RecordIssuesStep/help-referenceJobName.html
plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/RecordIssuesStep/help-sourceDirectory.html
plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/ScanForIssuesStep/help-referenceJobName.html
plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/ScanForIssuesStep/help-sourceDirectory.html
plugin/src/test/java/io/jenkins/plugins/analysis/core/testutil/IntegrationTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/StepsITest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/StepsOnAgentITest.java
plugin/src/test/resources/io/jenkins/plugins/analysis/warnings/steps/clair.json

Update terminology per [JENKINS-65398](https://issues.jenkins.io/browse/JENKINS-65398
)

[JENKINS-65398] Terminology update

---

plugin/src/main/resources/io/jenkins/plugins/analysis/warnings/charts.jelly

Setting the correct "for" attribute enables us to click the text of a radio button instead of the radio button itself.

Fix labels for radio buttons chart configuration

---

ui-tests/pom.xml

Bump Jenkins version for UI tests to 2.303.3

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/util/ModelValidation.java
plugin/src/main/resources/io/jenkins/plugins/analysis/core/util/Messages.properties
plugin/src/test/java/io/jenkins/plugins/analysis/core/util/ModelValidationTest.java

See [JENKINS-67617](https://issues.jenkins.io/browse/JENKINS-67617) for and [Jenkins Security Advisory](https://www.jenkins.io/security/advisory/2022-01-12/) details.

[JENKINS-67617] Add dot as valid character in IDs

---

.github/workflows/ci.yml
plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/ResultAction/summary.jelly
plugin/src/main/resources/issues/log-messages.jelly

Some icons have been renamed in FontAwesome 6.x.

Fix icon names for FontAwesome 6.x.

---

.github/workflows/ci.yml
plugin/pom.xml
ui-tests/pom.xml

Make plugin compatible with LTS releases 11 and 17.

Let CI run with JDK 11 and 17

---

plugin/pom.xml
plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/IssuesDetail/filled.jelly
plugin/src/main/resources/issues/history.jelly
ui-tests/src/main/java/io/jenkins/plugins/analysis/warnings/AnalysisResult.java

Otherwise previous and next buttons will not adapt to the selected Jenkins theme.

Use new theme-aware carousel component of BS plugin

---

plugin/pom.xml
plugin/src/main/resources/io/jenkins/plugins/analysis/core/columns/IssuesTotalColumn/column.jelly

Use new styles of jenkinsci/jenkins#5851 in the warnings plugin.

Use new Jenkins table styling for tooltips

---

plugin/pom.xml
plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/IssuesDetail/filled.jelly
plugin/src/main/resources/issues/property-tab.jelly
plugin/src/main/resources/issues/property.jelly

Downstream PR of https://github.com/jenkinsci/bootstrap5-api-plugin/pull/158.

Use new Jenkins styles for Boostrap tabs

---

plugin/src/main/webapp/js/issues-detail.js

The Bootstrap attribute changed from `href` to `data-bs-target`.

Fix saving of active tab in browser local storage

---

plugin/pom.xml
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/AnalysisStepDescriptor.java

Resolves [JENKINS-68336](https://issues.jenkins.io/browse/JENKINS-68336)
Multibranch Pipelines do not inherit from AbstractProject but from ComputedFolder. The next similar super class of both ComputedFolder and AbstractProject is BuildableItem.

Make AncestorInPath Object include Multibranch pipelines

---

plugin/src/main/resources/io/jenkins/plugins/analysis/core/columns/IssuesTotalColumn/column.jelly

Make new Tippy tooltip interactive

---

plugin/src/main/java/io/jenkins/plugins/analysis/warnings/axivion/AxRawIssue.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/axivion/AxivionParser.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/axivion/AxivionSuite.java
plugin/src/main/resources/io/jenkins/plugins/analysis/warnings/axivion/AxivionSuite/config.jelly
plugin/src/main/resources/io/jenkins/plugins/analysis/warnings/axivion/AxivionSuite/config.properties
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/axivion/AxivionParserTest.java
plugin/src/test/resources/io/jenkins/plugins/analysis/warnings/axivion/sv_justified_and_suppressed.json

This PR introduces a backward compatible new field which ignores importing suppressed or justified issues.
This is now the default behavior as it is in the Axivion Dashboard.

[Axivion-Tool] Introduce field to exclude suppressed or justified issues

---

plugin/src/main/java/io/jenkins/plugins/analysis/warnings/SimulinkCheckParse.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/ParsersITest.java
plugin/src/test/resources/io/jenkins/plugins/analysis/warnings/steps/simulink.html

This pull request is to include a parser for .html report files generated from Simulink Check Code Generator.
This request is linked analysis-model pull request: https://github.com/jenkinsci/analysis-model/pull/865

Include Parser for Simulink Check Code Generator

---

plugin/pom.xml

All versions use the correct baseline now.

Get versions of dependencies from BOM

---

plugin/pom.xml
plugin/src/main/java/io/jenkins/plugins/analysis/core/tokens/IssuesSizeTokenMacro.java

Remove fixed version of echarts

---

plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/AffectedFilesResolverITest.java
ui-tests/pom.xml
ui-tests/src/main/java/io/jenkins/plugins/analysis/warnings/AnalysisResult.java
ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/DetailsTabUiTest.java
ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/UiTest.java

Verified ATH locally on Chrome for Jenkins 2.437 and ATH 770.v81b_784f28b_d7.

Bump ATH and Jenkins versions

---

plugin/pom.xml
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/ResetQualityGateCommand.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/ResetQualityGateCommandTest.java

See [JENKINS-72305](https://issues.jenkins.io/browse/JENKINS-72305) for details.

[JENKINS-72305] Fix permission for reset quality gate action

---

plugin/pom.xml
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/ParsersITest.java
plugin/src/test/resources/io/jenkins/plugins/analysis/warnings/steps/parasoft.xml

See 
- https://github.com/jenkinsci/parasoft-findings-plugin
- https://issues.jenkins.io/browse/JENKINS-62113
- https://issues.jenkins.io/browse/JENKINS-64789

Add an integration test for the parser of the parasoft-findings plugin

---

doc/Custom-Plugin.md

Replaces the  JSR 305 `@Nonnull` annotations in the custom plugin code example.
None – docs only.
```[tasklist]
```

Update custom plugin code example

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/model/AggregationAction.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/model/FixedWarningsDetail.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/IssuesPublisher.java
plugin/src/main/java/io/jenkins/plugins/analysis/core/util/WarningsQualityGateEvaluator.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/CodeGenerator.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/CrossCoreEmbeddedStudio.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/EmbeddedEngineer.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/OwaspDependencyCheck.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/RfLint.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/SimulinkCheck.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/axivion/AxivionSuite.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/axivion/RemoteAxivionDashboard.java
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/groovy/DynamicDocumentParser.java
plugin/src/test/java/io/jenkins/plugins/analysis/core/model/TabLabelProviderTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/axivion/AxivionSuiteSerializationTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/axivion/AxivionSuiteTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/groovy/GroovyScriptITest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/groovy/ParserConfigurationITest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/groovy/ParserConfigurationTest.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/tasks/TaskScannerBenchmark.java
ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/SmokeTests.java
ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/UiTest.java

Introduced by new CheckStyle empty lines rule.

Fix warnings

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/steps/ScanForIssuesStep.java

All steps should use the same parameter name.

Use the correct property name `skipBlames`

---

plugin/pom.xml

See https://issues.jenkins.io/browse/JENKINS-72493.

[JENKINS-72493] Use json-path-api plugin

---

plugin/pom.xml
plugin/src/main/java/io/jenkins/plugins/analysis/warnings/axivion/RemoteAxivionDashboard.java

See https://plugins.jenkins.io/asm-api/

Use ASM API plugin as dependency

---

plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/FixedWarningsDetail/fixed-warnings-data-table.js
plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/FixedWarningsDetail/index.jelly

https://issues.jenkins.io/browse/JENKINS-74008
I'm not able to find a way to make fixed issues appear. I've had a bunch of PMD issues in the project I had been testing this against, but fixing them only makes the list of violations shorter. If someone points me to how I can make fixed issues appear I'd be happy to test that scenario and record my screen.
[Before the change](https://www.youtube.com/watch?v=SQoHr6VZ0kk)
[After the change](https://www.youtube.com/watch?v=BBDuIZCvpJg)

[JENKINS-74008] Extract JavaScript block from `FixedWarningsDetail/index.jelly`

---

package.json
plugin/src/main/resources/io/jenkins/plugins/analysis/core/model/ResultAction/summary.jelly

Replace YUI button class with Jenkins default button class for reset reference build action

---

plugin/src/main/resources/io/jenkins/plugins/analysis/core/steps/PublishIssuesStep/config.jelly

See [JENKINS-74900](https://issues.jenkins.io/browse/JENKINS-74900).

Add missing `scm` property in configuration screen

---

plugin/pom.xml

Depends on jsoup API plugin
CI

Depends on jsoup API plugin

---

doc/Documentation.md
plugin/pom.xml

Jenkins BOM contains all correct versions again.

Remove all BOM versions that are now up to date

---

plugin/src/main/java/io/jenkins/plugins/analysis/core/model/MissingResultFallbackHandler.java
plugin/src/test/java/io/jenkins/plugins/analysis/warnings/steps/JobActionITest.java

The `MissingResultFallbackHandler` scans the build history of a job for `ResultAction`s to provide trend charts even for jobs that have no valid result in the last build. It makes sense to look only at the last couple of builds for such actions. Otherwise, too many builds need to be serialized in the Jenkins controller: this will lead to performance problems.
Fixes https://issues.jenkins.io/browse/JENKINS-75647

[JENKINS-75647] Use only 5 builds when scanning the history for actions

---

plugin/src/main/resources/issues/log-messages.jelly
plugin/src/main/webapp/css/custom-style.css

A follow up to https://github.com/jenkinsci/warnings-ng-plugin/pull/2067#discussion_r2239935734. As far as I can tell the information log messages are a shortcut view of the `/info` route.
If there are any others I can also make similar changes, this was just the one I noticed.
Tested against the projects provided in https://github.com/uhafner/warnings-ng-plugin-devenv

Expand information messages card

---

.github/workflows/cd.yml

Add missing CD pipeline

---

pom.xml

See https://github.com/jenkinsci/warnings-ng-plugin/pull/2086 and https://github.com/jenkinsci/warnings-ng-plugin/pull/2086#issuecomment-3187398462

Do not deploy parent pom

---

ui-tests/pom.xml

Do not deploy UI tests pom

---

plugin/pom.xml
pom.xml
ui-tests/src/main/java/io/jenkins/plugins/analysis/warnings/AnalysisResult.java

Fix deployment of plugin artifact during CD.

Skip deployment only for parent module
